
Running GA...
Generation Evaluation      Worst       Best     Median    Average    Std Dev
---------- ---------- ---------- ---------- ---------- ---------- ----------
         0          5 0.79710144 0.87391304 0.84057971 0.83507246 0.02585078
[2.119415371409548, -3.495174109273477, -8.158454749309836, 0.7056972971346729, 1, 184.63574478808067, 19.26981742776234] : 0.844927536231884
[2.6674281891319063, -3.6834210994739753, -9.041677085318364, 0.48306734602219675, 1, 141.51669519328135, 19.23190867478837] : 0.7971014492753623
[1.7261337611888328, -3.0362181634778165, -8.067862076552995, 0.7284859350012776, 0, 180.56126829555762, 19.46827131408122] : 0.8739130434782609
[2.697937728755412, -3.306160906982135, -7.547335150320398, 0.6008140682663606, 3, 137.59337797972242, 10.485659565023349] : 0.818840579710145
[1.4510794789281234, -3.814668736344772, -8.69737502311797, 0.5836408724181461, 3, 102.96721576959567, 28.892988679233365] : 0.8405797101449275
Best training fitness =  0.8739130434782609
DONE.
[2022-08-06 20:02:37] INFO (GraphClassifier/MainThread) Ensemble argument on, will try using ensemble model.
C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\solver\utils.py:90: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.perform_dict = self.perform_dict.append(new, ignore_index=True)
C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\solver\utils.py:90: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.perform_dict = self.perform_dict.append(new, ignore_index=True)
Traceback (most recent call last):
  File "C:\Users\flori\OneDrive\Desktop\Data Science\Bio-Inspired AI\Project\Bio-AI-project\run.py", line 72, in <module>
    main()
  File "C:\Users\flori\OneDrive\Desktop\Data Science\Bio-Inspired AI\Project\Bio-AI-project\run.py", line 68, in main
    app.launch(alg='GA', dataset='MUTAG', graph_model=['gcn'], hidden_layers=1, problem='graph')
  File "C:\Users\flori\OneDrive\Desktop\Data Science\Bio-Inspired AI\Project\Bio-AI-project\autogl_ea\app.py", line 36, in launch
    __solve(optimizer, dataset, graph_model, search_space, device, problem)
  File "C:\Users\flori\OneDrive\Desktop\Data Science\Bio-Inspired AI\Project\Bio-AI-project\autogl_ea\app.py", line 109, in __solve
    acc = solver.evaluate(metric='acc')
  File "C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\solver\classifier\graph_classifier.py", line 660, in evaluate
    predicted = self.predict_proba(dataset, inplaced, inplace, use_ensemble, use_best, name, mask)
  File "C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\solver\classifier\graph_classifier.py", line 513, in predict_proba
    self._predict_proba_by_name(dataset, model_name, mask)
  File "C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\solver\classifier\graph_classifier.py", line 543, in _predict_proba_by_name
    self.trained_models[name]
  File "C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\module\train\graph_classification_full.py", line 388, in predict_proba
    loader = utils.graph_get_split(
  File "C:\Users\flori\anaconda3\envs\bio_venv\lib\site-packages\autogl\datasets\utils\_general.py", line 355, in graph_get_split
    raise ValueError(f"Provided dataset do NOT have {mask} split")
ValueError: Provided dataset do NOT have test split